### ISSUE TITLE
The 'location' property is not allowed

### ISSUE THREAD

**Issue by vRune4** [Azure/bicep-deploy#102]
```
Action config: {
  "type": "deployment",
  "name": "myproject",
  "location": "norwayeast",
  "templateFile": "/home/runner/work/myproject/myproject/infra/main.bicep",
  "parametersFile": "/home/runner/work/myproject/myproject/infra/main.dev.bicepparam",
  "parameters": {
    "environment": "dev",
    "serviceName": "veilederen",
    "dockerImageName": "company/myproject:1.2.0-PullRequest111.2-0d859af"
  },
  "tags": {},
  "maskedOutputs": [],
  "operation": "create",
  "scope": {
    "type": "resourceGroup",
    "subscriptionId": "***",
    "resourceGroup": "rg-myproject-dev"
  },
  "whatIf": {
    "excludeChangeTypes": []
  }
}
```

// exp: Should deploy just fine
// act: 
Error: Request failed. CorrelationId: 7162b451-fbdc-434d-a171-959ee36e2b27
Error: {
  "code": "InvalidDeployment",
  "message": "The 'location' property is not allowed for 'myproject' at resource group scope. Please see https://aka.ms/arm-deployment-subscription for usage details."
}

This is a project that I have deployed successfully using the old azure/arm-deploy@v2 action. The main difference is that I've now added a main.dev.bicepparam file (which sets the location to a default).

**Comment by anthony-c-martin** [comment]
@vRune4 does this work if you avoid setting the "location" property in the `yml` configuration? It's not required by the service, because the location of the resource group is always used instead.

**Comment by vRune4** [comment]
Thank you @anthony-c-martin. That got me back on track.

One of the things that confused me originally was that VSCode got upset with me:
![Image](https://github.com/user-attachments/assets/1f29d63d-7ea1-4614-b64f-20c9e4aab21c)
