### ISSUE TITLE
[BUG] Unable to resolve action `Azure/bicep-deploy@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by AndreasAugustin** [Azure/bicep-deploy#65]
Within the documentation it is stated to use `v1`: https://github.com/Azure/bicep-deploy?tab=readme-ov-file#usage

Actually there are no tags nor releases available.

using the branch `main` is actually working.

**Comment by anthony-c-martin** [comment]
You've jumped the gun a little bit - we haven't actually released this yet 😄. We're preparing to release this week - after which you should be able to use it.

**Comment by anthony-c-martin** [comment]
Should be working now!
