### ISSUE TITLE
Incorrect Formatting in "What-If" Output

### ISSUE THREAD

**Issue by Latzox** [Azure/bicep-deploy#71]
**Description**
The action is displaying the "what-if" changes incorrectly. Instead of showing structured changes, the output is displayed letter by letter, making it difficult to read and understand.

**Steps to Reproduce**
1. Run the "bicep deploy" GitHub action with "what-if" enabled to preview changes.
2. Observe the output, which displays each change as individual letters rather than a full line or structured format.

**Expected Behavior**
The "what-if" changes should be displayed in a clear, structured format (e.g., line by line or by property), allowing for easy review of changes.

**Actual Behavior**
See workflow run: https://github.com/Latzox/quickstart-azure-app-service-api/actions/runs/11662846647/job/32470028349
Or screenhot below:
![Image](https://github.com/user-attachments/assets/ffdc4876-7744-4674-b777-9ba64dd272c9)

**Additional infos**
```
Action config: {
  "type": "deployment",
  "name": "11662846647",
  "location": "switzerlandnorth",
  "templateFile": "/home/runner/work/quickstart-azure-app-service-api/quickstart-azure-app-service-api/deploy/main.bicep",
  "parameters": {
    "subIdSharedServices": "***",
    "subIdSampleApi": "***"
  },
  "tags": {},
  "maskedOutputs": [],
  "operation": "whatIf",
  "scope": {
    "type": "subscription",
    "subscriptionId": "***"
  },
  "whatIf": {
    "excludeChangeTypes": []
  }
}
Installed Bicep version 0.30.[23](https://github.com/Latzox/quickstart-azure-app-service-api/actions/runs/11662846647/job/32470028349#step:5:24) to /tmp/bicep
```

Pipeline definition:
```
- name: Preview Deployment
        uses: azure/bicep-deploy@v1
        with:
          type: deployment
          operation: whatIf
          name: ${{ github.run_id }}
          location: ${{ env.AZURE_REGION }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: deploy/main.bicep
          parameters: |
            {
              "subIdSharedServices": "${{ secrets.AZURE_SUBSCRIPTION_ID_SS }}",
              "subIdSampleApi": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
```

**Comment by anthony-c-martin** [comment]
Thanks for reporting this!

**Comment by Latzox** [comment]
@anthony-c-martin I can confirm that it works now as expected. You can see it in this workflow run:

https://github.com/Latzox/quickstart-azure-app-service-api/actions/runs/11685472901/job/32538991847

Thank you for the quick resolution!
